void core_load(const char *sofile);
void core_load_game(const char *filename);
size_t core_get_memory_size(unsigned id);
void *core_get_memory_data(unsigned id);
void core_run();
float core_get_nominal_fps(void);
void core_unload();
void core_message_update(void);
const char *core_message_text(void);
int core_message_frames(void);
