name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

defaults:
  run:
    shell: bash

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update -q
      - run: sudo apt-get install libopenal-dev xorg-dev libgl1-mesa-dev libglfw3-dev -y --allow-unauthenticated
      - run: make

  build_osx:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: brew install openal-soft glfw3
      - run: make

  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: choco install wget --ignore-checksums
      - run: wget --no-check-certificate http://www.openal-soft.org/openal-binaries/openal-soft-1.21.0-bin.zip
      - run: 7z x openal-soft-1.21.0-bin.zip -o/c/
      - run: wget https://github.com/glfw/glfw/releases/download/3.3.4/glfw-3.3.4.bin.WIN64.zip
      - run: 7z x glfw-3.3.4.bin.WIN64.zip -o/c/
      - run: echo "CFLAGS=-I\"/c/openal-soft-1.21.0-bin/include/\" -I\"/c/glfw-3.3.4.bin.WIN64/include/\"" >> $GITHUB_ENV
      - run: echo "LDFLAGS=-L\"/c/openal-soft-1.21.0-bin/libs/Win64/\" -L\"/c/glfw-3.3.4.bin.WIN64/lib-mingw-w64/\"" >> $GITHUB_ENV
      - run: CC=gcc make
