name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

defaults:
  run:
    shell: bash

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: choco install wget 7zip -y --ignore-checksums
      - run: mkdir lib
      - run: wget --no-check-certificate http://www.openal-soft.org/openal-binaries/openal-soft-1.21.0-bin.zip
      - run: 7z x openal-soft-1.21.0-bin.zip -o/c/
      - run: cp /c/openal-soft-1.21.0-bin/libs/Win64/* ./lib
      - run: wget https://github.com/glfw/glfw/releases/download/3.3.4/glfw-3.3.4.bin.WIN64.zip
      - run: 7z x glfw-3.3.4.bin.WIN64.zip -o/c/
      - run: cp /c/glfw-3.3.4.bin.WIN64/lib-mingw-w64/libglfw3* ./lib
      - run: cp /c/glfw-3.3.4.bin.WIN64/lib-mingw-w64/glfw3.dll .
      - run: echo "CFLAGS=-I\"/c/openal-soft-1.21.0-bin/include/\" -I\"/c/glfw-3.3.4.bin.WIN64/include/\"" >> $GITHUB_ENV
      - run: echo "LDFLAGS=-L./lib" >> $GITHUB_ENV
      - run: CC=gcc make
      - uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: |
            ./*.exe
            ./lib/*